# Generated by Django 3.1.2 on 2020-10-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='developers',
        ),
        migrations.AddField(
            model_name='developers',
            name='team',
            field=models.ForeignKey(default='Training', on_delete=django.db.models.deletion.CASCADE, to='project.teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='location',
            field=models.CharField(default='Bng', max_length=50),
            preserve_default=False,
        ),
    ]
