# Generated by Django 3.1.2 on 2020-10-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_developers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.teams'),
        ),
    ]
